# Generated by Django 2.0.6 on 2018-06-19 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_IG', models.CharField(max_length=20)),
                ('resume', models.TextField()),
                ('details', models.TextField()),
                ('statut', models.IntegerField()),
            ],
            options={
                'verbose_name': "Details de l'étude",
                'ordering': ['ID_IG'],
            },
        ),
        migrations.CreateModel(
            name='T_IG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_IG', models.CharField(max_length=20)),
                ('postes', models.CharField(max_length=255)),
                ('ouvrages', models.TextField(null=True)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date début IG')),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date fin IG')),
            ],
            options={
                'verbose_name': 'Informations sur IG depuis SPORT',
                'ordering': ['date_debut'],
            },
        ),
    ]
