# Generated by Django 2.0.6 on 2018-06-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='t_details',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.T_statut'),
        ),
    ]
