# Generated by Django 2.0.6 on 2018-06-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180619_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_details',
            name='statut',
        ),
        migrations.AlterModelOptions(
            name='t_ig',
            options={'ordering': ['date_debut'], 'verbose_name': 'Détails IG et étude'},
        ),
        migrations.AddField(
            model_name='t_ig',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='t_ig',
            name='resume',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='t_ig',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.T_statut'),
        ),
        migrations.AlterField(
            model_name='t_ig',
            name='postes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='T_details',
        ),
    ]
